openapi: "3.1.0"
info:
  title: "A getting started API"
  version: "1.0.0"
servers:
  - url: "http://localhost:3000"
paths:   
  /users:
    get:
      operationId: getUsers
      summary: "Get a list of users"
      responses:
        '200':
          description: "Successful response"
          content:
            application/json:
              example:
                - id: "1"
                  first_name: "John"
                  last_name: "Doe"
                  name: "John Doe"
                  display_name: "JohnD"
                  email: "john.doe@example.com"
                  date_of_birth: "1990-01-01"
                  avatar_url: "https://example.com/avatar.jpg"
                  personal_phone_number: "123-456-7890"
                  work_email: "john.doe@work.com"
components:
  schemas:
    User:
      required: ["id", "first_name", "last_name", "name", "display_name", "email"]
      type: "object"
      properties:
        id:
          type: "string"
          description: "The user's unique identifier"
        first_name:
          type: "string"
          description: "The user's first name"
        last_name:
          type: "string"
          description: "The user's last name"
        name:
          type: "string"
          description: "The user's preferred name"
        display_name:
          type: "string"
          description: "The user's preferred display name"
        email:
          type: "string"
          description: "Email address"
        date_of_birth:
          type: "date"
          description: The user's date of birth
        avatar_url:
          type: string
          description: The user's avatar photo
        personal_phone_number:
          type: string
          description: The user's phone number
        work_email: 
          type: string
          description: The user's work email