openapi: "3.1.0"
info:
  title: "StackOne Unified API"
  version: "1.0.0"
  description: Return transformed employee data from Bamboo Hr API
servers:
  - url: "/"
paths:   
  /employees:
    get:
      parameters:
      - in: query
        name: api_key
        required: true
        schema:
          type: string
        description: The users api key
      - in: query
        name: offset
        required: false
        schema:
          type: integer
        description: The number of items to skip before starting to collect the result set
      - in: query
        name: limit
        required: false
        schema:
          type: integer
        description: The numbers of items to return
      tags:
          - Employees
      operationId: getEmployees
      summary: "Get a list of employees with user information"
      responses:
        '200':
          description: "Successful response"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Employee'
              example:
                - id: "1"
                  firstName: "John"
                  lastName: "Doe"
                  name: "John Doe"
                  displayName: "JohnD"
                  workEmail: "john.doe@example.com"
                  dateOfBirth: "1990-01-01"
                  avatarUrl: "https://example.com/avatar.jpg"
                  personalPhoneNumber: "123-456-7890"
                  workEmail: "john.doe@work.com"
                  jobTitle: "HR Manager"
                  department: "Human Resources"
                  managerId: 6
                  startDate: "2023-03-10"
                  tenure: 0
                  workAnniversary: "2024-03-10"
components:
  schemas:
    Employee:
      required: ["id", "first_name", "last_name", "name", "display_name", "personal_phone_number", "work_email", "department"]
      type: "object"
      properties:
        id:
          type: "string"
          description: "The employee's unique identifier"
        firstName:
          type: "string"
          description: "The employee's first name"
        lastName:
          type: "string"
          description: "The employee's last name"
        name:
          type: "string"
          description: "The employee's preferred name"
        displayName:
          type: "string"
          description: "The employee's preferred display name"
        email:
          type: "string"
          description: "Email address"
        dateOfBirth:
          type: "string"
          format: "date"
          description: "The employee's date of birth"
        avatarUrl:
          type: "string"
          description: "The employee's avatar photo"
        personalPhoneNumber:
          type: "string"
          description: "The employee's phone number"
        workEmail: 
          type: "string"
          description: "The employee's work email"
        jobTitle:
          type: "string"
          description: "The employee's job title"
        department: 
          type: "string"
          description: "The employee's department"
        managerId:
          type: "number"
          description: "The unique identifier of the employee's manager"
        startDate:
          type: "string"
          format: "date"
          description: "The employee's start date"
        tenure:
          type: "number"
          description: "The number of years the employee has been at the business"
        workAnniversary:
          type: "string"
          format: "date"
          description: "The employee's next work anniversary"